### ISSUE TITLE
GameSystem / RoyalGameOfUr : ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by Zomis** [Zomis/Server2#10]
From my logs:

```
[2018-04-05 14:51:07,582] ERROR net.zomis.core.events.ListenerList [WebSocketWorker-11] - Problem when handling event IllegalMoveEvent(game=net.zomis.games.server2.games.Game@11ecb94d, player=-1, moveType=roll, move=-1, reason=Not your turn) in (net.zomis.games.server2.games.IllegalMoveEvent) -> kotlin.Unit
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at net.zomis.games.server2.games.GameSystem$7.invoke(GameSystem.kt:114)
	at net.zomis.games.server2.games.GameSystem$7.invoke(GameSystem.kt:62)
	at net.zomis.core.events.ListenerList.execute(EventSystem.kt:20)
	at net.zomis.core.events.EventSystem.execute(EventSystem.kt:49)
	at net.zomis.games.server2.games.impl.RoyalGameOfUrSystem$Companion$init$1.invoke(RoyalGameOfUrSystem.kt:27)
	at net.zomis.games.server2.games.impl.RoyalGameOfUrSystem$Companion$init$1.invoke(RoyalGameOfUrSystem.kt:11)
	at net.zomis.core.events.ListenerList.execute(EventSystem.kt:20)
	at net.zomis.core.events.EventSystem.execute(EventSystem.kt:49)
	at net.zomis.games.server2.games.GameSystem$1.invoke(GameSystem.kt:78)
	at net.zomis.games.server2.games.GameSystem$1.invoke(GameSystem.kt:62)
	at net.zomis.core.events.ListenerList.execute(EventSystem.kt:20)
	at net.zomis.core.events.EventSystem.execute(EventSystem.kt:49)
	at net.zomis.games.server2.Server2$start$3.invoke(Server2.kt:50)
	at net.zomis.games.server2.Server2$start$3.invoke(Server2.kt:36)
	at net.zomis.core.events.ListenerList.execute(EventSystem.kt:20)
	at net.zomis.core.events.EventSystem.execute(EventSystem.kt:49)
	at net.zomis.games.server2.ws.Server2WS.onMessage(Server2WS.kt:37)
	at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:469)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:368)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:657)
```

One reason why this happened is that it is possible to matchmake against yourself - prevent this in SimpleMatchMakingSystem

Another thing that can be done is to have a check in the failing line in GameSystem - if array is out of bounds, then send "IllegalMove" back instead of trying to handle this.

**Comment by Zomis** [comment]
I don't *think* this is happening anymore.
